### PR TITLE
Seolhalee patch 1

### PR DESCRIPTION
**Pull request by seolhalee**
Add codes for Spain and Czech with required data files

### CODE REVIEW

**Review by ar0ch — APPROVED** [review]

**Comment by ar0ch** [comment]
Thanks Seolha.  You can `Squash and merge` whenever you're ready

**Comment by seolhalee** [comment]
Aroon, I see a message that I'm not authorized to merge this pull request.

**Comment by ar0ch** [comment]
Ooh, I might have messed up the branch protection setting.  Could you try again?

**Comment by seolhalee** [comment]
Yay it worked! Thanks.

**Pull request merged**
