### PR TITLE
County vaccine layer

### PR DESCRIPTION
**Pull request by freyja-bt**
Unable to test it, but everything should at least be present for it to work, even if things need to be changed.

### CODE REVIEW

**Review by ar0ch — APPROVED** [review]
LGTM for initial merge

**Comment by ar0ch** [comment]
@freyja-bt could you pull the latest `geomUnitedStates.geojson` from the master branch of this repo and make sure it works in your test env?  If it does, please check in the master file from this repo into your branch.

**Comment by freyja-bt** [comment]
@ar0ch The geojson is different because we accounted for Joplin and Kansas City. The branch's "geomUnitedStates.geojson" includes those cities, while the branch's "geomUnitedStatesCV.geojson" is equivalent to the original geojson (because we don't have accurate vaccine data for Joplin and KC).

**Comment by sjbeckett** [comment]
@ar0ch @freyja-bt just a note that I think the geojsons also differ due to #49. Changes here were to help fix the viz of the Hoonah-Angoon plus Yakutat geom; which overlapped with the unused county geoms in this area. Everything else should be the same.

**Pull request merged**
